### ISSUE TITLE
Trouble using 'jsonstreamer` with 'yajl' on Windows 10

### ISSUE THREAD

**Issue by mitendraanand** [kashifrazzaqui/json-streamer#12]
Hey @kashifrazzaqui

I have been trying to use your library json-streamer for implementing a Streaming API..

As directed, I have installed yajl on my Windows 10 system and installed it as below:

C:\Users\mianand\Downloads\lloyd-yajl-2.1.0-0-ga0ecdde\lloyd-yajl-66cb08c\build>nmake install

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

[ 30%] Built target yajl_s
[ 60%] Built target yajl
[ 66%] Built target yajl_test
[ 72%] Built target gen-extra-close
[ 78%] Built target json_reformat
[ 84%] Built target json_verify
[ 90%] Built target parse_config
[100%] Built target perftest
Install the project...
-- Install configuration: "Release"
-- Up-to-date: C:/Program Files (x86)/YetAnotherJSONParser/lib/yajl.lib
-- Up-to-date: C:/Program Files (x86)/YetAnotherJSONParser/lib/yajl.dll
-- Up-to-date: C:/Program Files (x86)/YetAnotherJSONParser/lib/yajl_s.lib
-- Up-to-date: C:/Program Files (x86)/YetAnotherJSONParser/include/yajl/yajl_parse.h
-- Up-to-date: C:/Program Files (x86)/YetAnotherJSONParser/include/yajl/yajl_gen.h
-- Up-to-date: C:/Program Files (x86)/YetAnotherJSONParser/include/yajl/yajl_common.h
-- Up-to-date: C:/Program Files (x86)/YetAnotherJSONParser/include/yajl/yajl_tree.h
-- Up-to-date: C:/Program Files (x86)/YetAnotherJSONParser/include/yajl/yajl_version.h
-- Up-to-date: C:/Program Files (x86)/YetAnotherJSONParser/share/pkgconfig/yajl.pc
-- Up-to-date: C:/Program Files (x86)/YetAnotherJSONParser/bin/json_reformat.exe
-- Up-to-date: C:/Program Files (x86)/YetAnotherJSONParser/bin/json_verify.exe

Still, on running the conda with python 3.6 gives me the following :

>>> from jsonstreamer import JSONStreamer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mianand\AppData\Local\Continuum\anaconda3\envs\pycharm_venv\lib\site-packages\jsonstreamer\__init__.py", line 9, in <module>
    from jsonstreamer.jsonstreamer import JSONStreamer, ObjectStreamer
  File "C:\Users\mianand\AppData\Local\Continuum\anaconda3\envs\pycharm_venv\lib\site-packages\jsonstreamer\jsonstreamer.py", line 14, in <module>
    from .yajl.parse import YajlParser, YajlListener, YajlError
  File "C:\Users\mianand\AppData\Local\Continuum\anaconda3\envs\pycharm_venv\lib\site-packages\jsonstreamer\yajl\parse.py", line 32, in <module>
    yajl = load_lib()
  File "C:\Users\mianand\AppData\Local\Continuum\anaconda3\envs\pycharm_venv\lib\site-packages\jsonstreamer\yajl\parse.py", line 29, in load_lib
    raise OSError('Yajl cannot be found.')
OSError: Yajl cannot be found.

Any pointers on this one ?
Help appreciated.

**Comment by kashifrazzaqui** [comment]
Sorry, I haven't tested this with windows. Should work with linux and mac systems.
