### ISSUE TITLE
Missing tests & tags

### ISSUE THREAD

**Issue by jayvdb** [kashifrazzaqui/json-streamer#13]
PyPI has 1.3.6 , and no tests.

GitHub only has a tag for v1.0.0 , so I cant use that.

Could you tag v1.3.6 in GitHub, so I can use it to get tests, and finish https://build.opensuse.org/package/show/home:jayvdb:py-new/python-jsonstreamer after https://github.com/kashifrazzaqui/again/issues/8 is also fixed.

**Comment by kashifrazzaqui** [comment]
Done, regret the inconvenience.

**Comment by jayvdb** [comment]
Thanks so much for very quick responses.  Both again and jsonstreamer are now ready for submission to openSUSE packaging.

I'm working on getting `mujson` into openSUSE, with whichever implementations are quite fast, and have reasonable test suites.

Currently jsonstreamer is missing from https://github.com/mattgiles/mujson/blob/master/mujson/__init__.py .  You might want to see if jsonstreamer is compatible and also use its benchmarking facility to check that it performs at least as well as the others already included - it should as it is based on yajl, like others which are already supported.

There is also `anyjson`, which looks quite unmaintained, and has a stricter API compliance requirement.
