### ISSUE TITLE
Partially parsing large items under dictionary key

### ISSUE THREAD

**Issue by soid** [kashifrazzaqui/json-streamer#16]
I have a large JSON that has a lot of items under certain dictionary key.
E.g.
```
{
"images": ["image1.jpg", "image2.jpg"],
"annotations: ["dog", "cat"]
}
```
The number of images and annotations values won't fit in memory. I'd like to iterate over them without loading all at once.
But it seems this library only loads a single key? E.g. the pair event is triggered once all "images" list is consumed.
Is it possible to use this library for a case like this?

**Comment by kashifrazzaqui** [comment]
Yes, you can use this library to parse infinitely large JSON without loading it in memory.  The library offers two APIs. A low level called JSONStreamer and a high level API called ObjectStreamer. Use the low level API to handle the case you want. An example is in the README.

**Comment by soid** [comment]
Could you explain more how partial reading is achieved? The example provided is not clear.
Here's my example:

```
json_object = """
    {
        "fruits":["apple","banana", "cherry"],
        "calories":[100,200,50]
    }
"""

def _catch_all(event_name, *args):
    print('\t{} : {}'.format(event_name, args))

object_streamer = jsonstreamer.ObjectStreamer()
object_streamer.add_catch_all_listener(_catch_all)
object_streamer.consume(json_object[0:40])
# we don't care about the rest cause we don't have enough memory to read all
object_streamer.close()
```

The partial input `json_object[0:40]` includes the "fruit" key and one full element "apple".
This only prints `object_stream_start : ()` but no `pair` event, cause, from my understanding, to fire the pair even it needs to read to the end of "fruit" list.

How can I catch reading this element "apple" only without reading to the end of the list?

**Comment by kashifrazzaqui** [comment]
https://github.com/kashifrazzaqui/json-streamer#jsonstreamer-example
