### ISSUE TITLE
Ensure exception __str__ methods return strings

### ISSUE THREAD

**Issue by mach-kernel** [kashifrazzaqui/json-streamer#3]
Hi there,

Issues that throw `JSONStreamerException` classes are difficult to debug because there is no expectation that a `str` will be returned. This makes debugging a PITA.
```
awesome_module.py", line 51, in map_step
    url + '\n' + str(e))
TypeError: __str__ returned non-string (type bytes)
```

**Comment by mach-kernel** [comment]
To fix, just do this to your string method: `str(e._msg.decode("utf-8"))`

**Comment by kashifrazzaqui** [comment]
Thanks for pointing this out, will make this change when I get a chance alternatively it would be great if you can generate a pull request and I will merge it in.

**Comment by kashifrazzaqui** [comment]
Fixed by PR from @mach-kernel
