### ISSUE TITLE
Trouble using 'jsonstreamer` with 'yajl-2' on Ubuntu 14.04

### ISSUE THREAD

**Issue by jig08** [kashifrazzaqui/json-streamer#5]
Hey @kashifrazzaqui

I have been trying to use your library `json-streamer` for implementing a Streaming API..

As directed, I have installed `yajl` on my Ubuntu 14.04 system and also verified it's presence and correct installation (refer:  [1] & [2])

Still, on running the command `python3 -m jsonstreamer.jsonstreamer < test.json` i.e. using it with `jsonstreamer` gives me the following :
```
  File "/usr/local/lib/python3.4/dist-packages/jsonstreamer/yajl/parse.py", line 29, in load_lib
    raise OSError('Yajl cannot be found.')
OSError: Yajl cannot be found.
```

Following up in https://github.com/lloyd/yajl/issues/190 it seems that there might be an issue in the `parse.py` file itself ? Maybe it's looking for `yajl1` and not `yajl2`.

Any pointers on this one ?
Help appreciated.

***
[1] Running `gcc -lyajl` yields:
```
jigyasa@spin:~$ gcc -lyajl
....
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

[2] And `sudo ldconfig -p | grep yajl` results in:
```
jigyasa@spin:~$ sudo ldconfig -p | grep yajl
	libyajl.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libyajl.so.2
```

**Comment by jig08** [comment]
@kashifrazzaqui 
So yes, I tweaked [jsonstreamer/yajl/parse.py#L23](https://github.com/kashifrazzaqui/json-streamer/blob/master/jsonstreamer/yajl/parse.py#L23) by adding compatibility for `yajl-2` as well and it works perfectly.

[jsonstreamer/yajl/parse.py#L23](https://github.com/kashifrazzaqui/json-streamer/blob/master/jsonstreamer/yajl/parse.py#L23) `for each in '', '.so', '.dylib':` was replaced by `for each in '', '.so', '.dylib', '.so.2':`

Sample run:

```
jigyasa@spin:~/tryHashkat/hashkat$ python3 -m jsonstreamer.jsonstreamer < test.json

event: doc_start
event: object_start
event: key	-> values: fruits
event: array_start
event: element	-> values: apple
event: element	-> values: banana
event: element	-> values: cherry
event: array_end
event: key	-> values: calories
event: array_start
event: element	-> values: 100
event: element	-> values: 200
event: element	-> values: 50
event: array_end
event: object_end
event: doc_end
```

**Comment by kashifrazzaqui** [comment]
Hey @jig08 thanks for the patch, I have merged it. Am closing this issue.

**Comment by jig08** [comment]
@kashifrazzaqui :smiley:

**Comment by rory09** [comment]
Hey, just FYI, I installed JSONStreamer via pip on Ubuntu 16.04 in a fresh conda environment (with all the usual anaconda installs (pandas etc.) and this error occurred again. I applied the same fix as above and it was sorted. 

Pip installed the following versions:

* jsonstreamer (1.3.6)
* yajl (0.3.5)

Should I have done something different than:

```sh
pip install jsonstreamer
``` 

To get a release that includes this patch? 

Or does PyPI need to be updated? (I don't know anything about PyPI governance / updating process, but thought it would be worth flagging).

Best,
Rory

**Comment by rory09** [comment]
After a little look around this repo and PyPI, I can see two potential causes:

* [PyPI's listing](https://pypi.python.org/pypi/jsonstreamer/1.3.6) for this package hasn't been updated since 2015, I'm not sure if that means the metadata hasn't changed, or that it hasn't pulled fresh code from github since then (again I'm a novice).
* The fix above has been merged to master, but not to a version tag, of which there is only one at [v1.0](https://github.com/kashifrazzaqui/json-streamer/tree/v1.0). Again, maybe this is causing the issue?

Thanks for the package, regardless!

**Comment by kashifrazzaqui** [comment]
@rory09 yes, this is indeed the problem I will push to PyPi when I get a chance

**Comment by rory09** [comment]
Fantastic, thank you :+1:

**Comment by piranna** [comment]
Can you publish a new version to PyPi?

**Comment by kashifrazzaqui** [comment]
@piranna  Done. v1.3.8

**Comment by piranna** [comment]
Thank you :-)
